apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Node.js
  labels:
    samples.operator.openshift.io/managed: "true"
  name: nodejs-angular
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      tags: builder,nodejs-angular
    from:
      kind: DockerImage
      name: docker.io/nodeshift/centos7-s2i-web-app:latest
    generation: 2
    importPolicy: {}
    name: "1"
    referencePolicy:
      type: Local
